export enum TransactionStatus {
  ROOT = 'ROOT',
  DVKD_WAITING_APPROVE = 'DVKD_WAITING_APPROVE',
  DVKD_WAITING_APPROVE_UPDATE = 'DVKD_WAITING_APPROVE_UPDATE',
  KSP_CV_WATING_APPROVE = 'KSP_CV_WATING_APPROVE',
  KSP_KSV_WAITING_APPROVE = 'KSP_KSV_WAITING_APPROVE',
  KSP_APPROVE = 'KSP_APPROVE',
  TRANS_REJECT = 'TRANS_REJECT',

}
