/**
 * Dịch vụ thẻ
 * Dịch vụ thẻ
 *
 * OpenAPI spec version: 1.0.0
 * Contact: https://lienvietpostbank.com.vn
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AccountLinkListOp { 
    /**
     * 001 - Mã PK
     */
    id: string;
    /**
     * 002 - Mã PK của Thẻ, tham chiếu tới đối tượng Card
     */
    cardId: string;
    /**
     * 003 - Mã PK của Thẻ phủ, tham chiếu tới đối tượng SupCard
     */
    supCardId?: string;
    /**
     * 004 - Mã PK của TK
     */
    accountId: string;
    /**
     * 005 - Ngày tạo
     */
    createdDate?: Date;
    /**
     * 006 - Mã PK người tạo
     */
    createdBy?: string;
    /**
     * 007 - Ngày cập nhật
     */
    modifiedDate?: Date;
    /**
     * 008 - Mã PK người cập nhật
     */
    modifiedBy?: string;
}
