import { ListAccount } from './Account';
import { AccountLinkList } from './AcountLinkList';

export class Card {
    id: string;
    account: ListAccount[];
    accountLinkList: AccountLinkList[];
    processId: string;
    accountId: string;
    accountNumber: string;
    accountIndex: string;
    cardTypeCode: string;
    cardTypeName: string;
    cardRateCode: string;
    cardRateName: string;
    cardProductCode: string;
    cardProductName: string;
    cardHolderName: string;
    cardNumber: string;
    contractNumber: string;
    deliveryTypeCode: string;
    deliveryTypeName: string;
    deliveryChanelCode: string;
    deliveryChanelName: string;
    deliveryBranchCode: string;
    deliveryBranchName: string;
    deliveryAddress: string;
    cardIssueFeeTypeCode: string;
    cardIssueFeeTypeName: string;
    feeAmount: number;
    totalAmount: number;
    vat: string;
    interestRate: string;
    secretQuestion: string;
    secretAnswer: string;
    explain: string;
    issueDate: string;
    expirationDate: string;
    employeeId: string;
    referrerCode: string;
    currentStatusCode: string;
    currentStatusName: string;
    changeStatusCode: string;
    changeStatusName: string;
    actionCode: string;
    actionName: string;
    createdDate: string;
    createdBy: string;
    createdByUserName: string;
    createdByFullName: string;
    createdByUserCore: string;
    modifiedDate: string;
    modifiedBy: string;
    modifiedByUserName: string;
    modifiedByFullName: string;
    modifiedByUserCore: string;
    countSupCard: string;
}
