/**
 * Dịch vụ thẻ
 * Dịch vụ thẻ
 *
 * OpenAPI spec version: 1.0.0
 * Contact: https://lienvietpostbank.com.vn
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountLinkListOp } from './accountLinkListOutputDTOUVoCaChcNngDanhSchTiKhonLinKtCaThChnhCaTiKhonLinKtCaTh';
import {ProcessIntegrated} from './ProcessIntegrated';


export interface CardDetailOutputDTOUVoCaChcNngChiTitCaThChnh {
    /**
     * 001 - Mã PK
     */
    id: string;
    /**
     * 002 - Danh sách tài khoản liên kết
     */
    accountLinkList?: Array<AccountLinkListOp>;
    /**
     * 003 - Mã PK hồ sơ giao dịch
     */
    processId: string;
    /**
     * 004 - Mã PK tài khoản mặc định
     */
    accountId: string;
    /**
     * 005 - Mã loại thẻ, tham chiếu tới đối tượng CardType
     */
    cardTypeCode: string;
    /**
     * 006 - Tên loại thẻ, tham chiếu tới đối tượng CardType
     */
    cardTypeName?: string;
    /**
     * 007 - Mã hạng thẻ, tham chiếu tới đối tượng CardRate
     */
    cardRateCode: string;
    /**
     * 008 - Tên hạng thẻ, tham chiếu tới đối tượng CardRate
     */
    cardRateName?: string;
    /**
     * 009 - Mã sản phẩm thẻ, tham chiếu tới đối tượng CardProduct
     */
    cardProductCode: string;
    /**
     * 010 - Tên sản phẩm thẻ, tham chiếu tới đối tượng CardProduct
     */
    cardProductName?: string;
    /**
     * 011 - Tên dập nổi
     */
    cardHolderName: string;
    /**
     * 012 - Số thẻ
     */
    cardNumber?: string;
    /**
     * 013 - Mã hợp đồng
     */
    contractNumber?: string;
    /**
     * 014 - Mã phát hành
     */
    cardHolderNumber?: string;
    /**
     * 015 - Mã hình thức phát hành, tham chiếu tới đối tượng DeliveryType
     */
    deliveryTypeCode: string;
    /**
     * 016 - Tên hình thức phát hành, tham chiếu tới đối tượng DeliveryType
     */
    deliveryTypeName?: string;
    /**
     * 017 - Mã nơi nhận thẻ, tham chiếu tới đối tượng DeliveryChanel
     */
    deliveryChanelCode: string;
    /**
     * 018 - Tên nơi nhận thẻ, tham chiếu tới đối tượng DeliveryChanel
     */
    deliveryChanelName?: string;
    /**
     * 019 - Mã chi nhánh nhận thẻ
     */
    deliveryBranchCode?: string;
    /**
     * 020 - Địa chỉ gửi nhận
     */
    deliveryAddress?: string;
    /**
     * 021 - Mã loại phí ATM, tham chiếu tới đối tượng CardIssueFee
     */
    cardIssueFeeTypeCode: string;
    /**
     * 022 - Tên loại phí ATM, tham chiếu tới đối tượng CardIssueFee
     */
    cardIssueFeeTypeName?: string;
    /**
     * 023 - Phí phát hành thẻ
     */
    feeAmount?: number;
    /**
     * 024 - Lãi suất
     */
    interestRate?: number;
    /**
     * 025 - Diễn giải
     */
    explain: string;
    /**
     * 026 - Ngày phát hành
     */
    issueDate?: Date;
    /**
     * 027 - Ngày hết hạn
     */
    expirationDate?: Date;
    /**
     * 028 - Mã nhân viên
     */
    employeeId: string;
    /**
     * 029 - Mã người giới thiệu
     */
    referrerCode: string;
    /**
     * 030 - Mã trạng thái hiện tại, tham chiếu tới đối tượng CardStatus
     */
    currentStatusCode?: CardDetailOutputDTOUVoCaChcNngChiTitCaThChnh.CurrentStatusCodeEnum;
    /**
     * 031 - Tên trạng thái hiện tại, tham chiếu tới đối tượng CardStatus
     */
    currentStatusName?: string;
    /**
     * 032 - Mã trạng thái thay đổi, tham chiếu tới đối tượng CardStatus
     */
    changeStatusCode?: CardDetailOutputDTOUVoCaChcNngChiTitCaThChnh.ChangeStatusCodeEnum;
    /**
     * 033 - Tên trạng thái thay đổi, tham chiếu tới đối tượng CardStatus
     */
    changeStatusName?: string;

    processIntegrated: ProcessIntegrated;
    /**
     * 034 - Mã chức năng, tham chiếu tới đối tượng CardAction
     */
    actionCode?: string;
    /**
     * 035 - Tên chức năng, tham chiếu tới đối tượng CardAction
     */
    actionName?: string;
    /**
     * 036 - Ngày tạo
     */
    createdDate?: Date;
    /**
     * 037 - Mã PK người tạo
     */
    createdBy?: string;
    /**
     * 038 - Ngày cập nhật
     */
    modifiedDate?: Date;
    /**
     * 039 - Mã PK người cập nhật
     */
    modifiedBy?: string;
}

// tslint:disable-next-line:no-namespace
export namespace CardDetailOutputDTOUVoCaChcNngChiTitCaThChnh {
    export type CurrentStatusCodeEnum = 'A' | 'I' | 'D';
    export const CurrentStatusCodeEnum = {
        A: 'A' as CurrentStatusCodeEnum,
        I: 'I' as CurrentStatusCodeEnum,
        D: 'D' as CurrentStatusCodeEnum
    };
    export type ChangeStatusCodeEnum = 'A' | 'I' | 'D';
    export const ChangeStatusCodeEnum = {
        A: 'A' as ChangeStatusCodeEnum,
        I: 'I' as ChangeStatusCodeEnum,
        D: 'D' as ChangeStatusCodeEnum
    };
}
