export enum SessionStorageKey {
  CURRENCY_STATUS = 'CURRENCY_STATUS',
  COUNTRY_STATUS = 'COUNTRY_STATUS',
  CUSTOMER_PASSPORT_STATUS = 'CUSTOMER_PASSPORT_STATUS',
  TRANSACTION_STATUS = 'TRANSACTION_STATUS',
}
