// default: true => hiển thị mặc định cột
export const HIDE_SHOW_TABLE = [
  {name: 'STT',                ticked: false, default: true},
  {name: 'Mã CN',              ticked: false, default: true},
  {name: 'Mã khách hàng',      ticked: false, default: true},
  {name: 'Customer Category',  ticked: false, default: false},
  {name: 'Mã tài sản',         ticked: false, default: false},
  {name: 'Mã sản phẩm',        ticked: false, default: true},
  {name: 'Tên chủ thẻ',        ticked: false, default: true},
  {name: 'SĐT',                ticked: false, default: true},
  {name: 'TK trích nợ',        ticked: false, default: true},
  {name: 'Số tiền trích nợ',   ticked: false, default: true},
  {name: 'Mã NVKD',            ticked: false, default: false},
  {name: 'Mã giới thiệu',      ticked: false, default: false},
  {name: 'Hạn mức',            ticked: false, default: true},
  {name: 'Họ và tên đệm',      ticked: false, default: false},
  {name: 'Tên',                ticked: false, default: false},
  {name: 'Ngày Sinh',          ticked: false, default: false},
  {name: 'Giới tính',          ticked: false, default: false},
  {name: 'số CMND',            ticked: false, default: false},
  {name: 'Ngày cấp',           ticked: false, default: false},
  {name: 'Nơi cấp',            ticked: false, default: false},
  {name: 'Email',              ticked: false, default: false},
  {name: 'Số nhà',             ticked: false, default: false},
  {name: 'Đường',              ticked: false, default: false},
  {name: 'Thành phố',          ticked: false, default: false},
  {name: 'Hạng thẻ',           ticked: false, default: false},
  {name: 'Trạng thái',         ticked: false, default: false},
  {name: 'Trạng thái duyệt',   ticked: false, default: false},
  {name: 'KSV',                ticked: false, default: false},
  {name: 'NHS',                ticked: false, default: false},
  {name: 'Ghi chú',            ticked: false, default: false},
  {name: 'Ngày Cấp HM',        ticked: false, default: true},
  {name: 'Thời gian cập nhật trên Uniform', ticked: false, default: true},
  {name: 'Lý do',              ticked: false, default: true},
];
