export const objCifDetail = {
    mis: {
        id: 'be22682e-f2f0-47a9-a187-4d0931cae3a8',
        customerId: '0cb5e71e-6346-457b-8e7a-e7ac39056f24',
        cifLoaiCode: '1000',
        cifLoaiName: 'QUY MO DOANH NGHIEP LON',
        cifLhktCode: '1100',
        cifLhktName: 'DOANH NGHIEP NHA NUOC TW',
        cifTpktCode: '1000',
        cifTpktName: 'CQ QUAN LY NHA NUOC TRUNG UONG',
        cifTctdCode: null,
        cifTctdName: null,
        cifKbhtgCode: '1000',
        cifKbhtgName: 'THANH VIEN HDQT',
        lhnnntvayCode: '000',
        lhnnntvayName: '000',
        tdManktCode: '6102',
        tdManktName: 'CONG TY TAI CHINH',
        cifNganhCode: '1000',
        cifNganhName: 'DICH VU HANG KHONG',
        cifKh78Code: '2000',
        cifKh78Name: 'KIEM TOAN VIEN',
        cifPnkhCode: '00',
        cifPnkhName: 'KHAC',
        comTsctCode: '1000',
        comTsctName: 'PHUONG TIEN VAN CHUYEN',
        dcGhCode: '01',
        dcGhName: 'KHOAN VAY DANG DUOC DIEU CHINH KY HAN',
        hhxnkCode: null,
        hhxnkName: null,
        loaiDnCode: null,
        loaiDnName: null,
        cifManktCode: '5811',
        cifManktName: 'XUAT BAN SACH',
        createdDate: '2021-10-29',
        createdBy: '6e03b996-dcf2-449e-a350-dbe3ede2ddd1',
        modifiedDate: '2021-10-29',
        modifiedBy: '6e03b996-dcf2-449e-a350-dbe3ede2ddd1'
    },

    udf: {
        id: 'bd35011a-8337-4de3-8e5f-977005d4f6d9',
        customerId: '0cb5e71e-6346-457b-8e7a-e7ac39056f24',
        canBoGioiThieu: null,
        cifPnkhCode: 'CNLONDK',
        cifPnkhName: 'Ca nhan lon dinh ky',
        tenDoiNgoai: null,
        website: null,
        email: null,
        dienThoai: null,
        tongSoLdHienTai: null,
        nganhNgheKinhDoanh: null,
        tenVietTat: null,
        hoTenVoChong: null,
        coCmndHc: null,
        ngayCapCmndHc: null,
        noiCapCmndHc: null,
        vonCoDinh: null,
        vonLuuDong: null,
        noPhaiThu: null,
        noPhaiTra: null,
        maHuyenThiXaCode: null,
        maHuyenThiXaName: null,
        viTriToLketVayvonCode: null,
        viTriToLketVayvonName: null,
        maTctdCode: null,
        maTctdName: null,
        tcKTctdCode: null,
        tcKTctdName: null,
        tongnguonvon: null,
        kyDanhGiaTvn: null,
        khachHangCode: null,
        khachHangName: null,
        loaiChuongTrinhCode: null,
        loaiChuongTrinhName: null,
        tuNgay: null,
        denNgay: null,
        thuongTatCode: null,
        thuongTatName: null,
        khutCode: null,
        khutName: null,
        lvUdCnCaoCifCode: null,
        lvUdCnCaoCifName: null,
        cnUtpt1483CifCode: null,
        cnUtpt1483CifName: null,
        dbKhVayCode: null,
        dbKhVayName: null,
        congTyNhaNuocCode: null,
        congTyNhaNuocName: null,
        groupCodeCode: null,
        groupCodeName: null,
        kenhTao: 'online',
        cifDinhdanhCode: null,
        cifDinhdanhName: null,
        dangkyDvGdemailDvkd: null,
        tongDoanhThu: null,
        khoiDonViGioiThieuCode: null,
        khoiDonViGioiThieuName: null,
        diaBanNongThonCode: null,
        diaBanNongThonName: null,
        maCbnvLpbCode: null,
        maCbnvLpbName: null,
        cifGiamDoc: null,
        cifKeToanTruong: null,
        comboSanPham2018Code: null,
        comboSanPham2018Name: null,
        expiredDate: null,
        pnkhKhdk: null,
        tracuuTtstkwebVivietCode: 'Y',
        tracuuTtstkwebVivietName: 'Yes',
        sdtNhanSmsGdtetkiem: '0989965583',
        soSoBaoHiemXaHoi: null,
        nguoiDaidienPhapluat: null,
        cmndCccdHc: null,
        nhanHdtQuaMail: null,
        createdDate: '2021-10-29',
        createdBy: '6e03b996-dcf2-449e-a350-dbe3ede2ddd1',
        modifiedDate: '2021-10-29',
        modifiedBy: '6e03b996-dcf2-449e-a350-dbe3ede2ddd1'
      },
};
