export const LIST_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DELETE: 'DELETE'
};
export const LIST_STATUS_CONTRACT = {
  ACCEPTED: 'ACCEPTED',
  REJECT: 'REJECT',
  WAITING_ACCEPT: 'WAITING_ACCEPT',
  DRAFT: 'DRAFT'
};
