export const LIST_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DELETE: 'DELETE'
};
export const LIST_STATUS_CONTRACT = {
  ACCEPTED: 'ACCEPTED',
  REJECT: 'REJECT',
  WAITING_ACCEPT: 'WAITING_ACCEPT',
  DRAFT: 'DRAFT'
};

export const LIST_STATUS_PROFILE_CUSTOMER = {
  SUCCESS: 'SUCCESS',
  UN_SUCCESS: 'UN_SUCCESS',
  UNCONFIRMED: 'UNCONFIRMED'
}

export const LIST_STATUS_CUSTOMER = {
  ACTIVE: 'ACTIVE',
  LOCK:'LOCK',
  DELETE:'DELETE'
}

export const LIST_STATUS_QR = {
  YES: 'YES',
  NO: 'NO'
}

export const LIST_STATUS_SEARCH = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
}
